### ISSUE TITLE
Overall Architecture Diagram of Cloud Deployment

### ISSUE THREAD

**Issue by justin-zhu1018** [nguyensjsu/fa21-172-group-7#7]

**Comment by islayshi** [comment]
Doing it in Lucidchart link here: https://lucid.app/lucidchart/a45fd2ae-2b7f-47ef-9027-b2a67fc748f1/edit?viewport_loc=-10%2C-10%2C1653%2C769%2C0_0&invitationId=inv_d123a33f-a130-4779-8608-9ac95ed2b50a 

It'll be exported as an image along with an explanation (?)

**Comment by islayshi** [comment]
![Overall Architecture Diagram of Cloud Deployment](https://user-images.githubusercontent.com/46005300/144658956-684cfdfa-71a6-42da-a964-9edc0c4eb71d.png)

Current Status ^^
